<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller; use App\Models\{AdminActivity,Customer,Order,Product}; use Illuminate\Http\Request; use Illuminate\Support\Facades\DB;
class OrderController extends Controller {
 public function index(Request $request){$q=Order::with(['customer','items'])->latest();if($request->status)$q->where('status',$request->status);if($request->search){$s=$request->search;$q->where(function($q)use($s){$q->where('order_number','like',"%$s%")->orWhereHas('customer',fn($c)=>$c->where('name','like',"%$s%")->orWhere('phone','like',"%$s%"));});}return $q->paginate($request->integer('per_page',20));}
 public function store(Request $request){$data=$request->validate(['customer.name'=>'required|string|max:255','customer.phone'=>'required|string|max:30','customer.email'=>'nullable|email|max:255','customer.address'=>'required|string|max:500','items'=>'required|array|min:1','items.*.product_id'=>'required|integer|distinct|exists:products,id','items.*.quantity'=>'required|integer|min:1|max:1000']); return DB::transaction(function()use($data){$c=Customer::updateOrCreate(['phone'=>$data['customer']['phone']],$data['customer']);$rows=[];$subtotal=0;foreach($data['items'] as $line){$p=Product::where('is_available',true)->findOrFail($line['product_id']);$lineTotal=$p->price*$line['quantity'];$subtotal+=$lineTotal;$rows[]=['product_id'=>$p->id,'product_name'=>$p->name,'quantity'=>$line['quantity'],'unit_price'=>$p->price,'subtotal'=>$lineTotal];}$order=Order::create(['order_number'=>'DG-'.now()->format('Ymd').'-'.strtoupper(\Illuminate\Support\Str::random(8)),'customer_id'=>$c->id,'subtotal'=>$subtotal,'total'=>$subtotal]);$order->items()->createMany($rows);return response()->json($order->load(['customer','items']),201);});}
 public function show(Order $order){return $order->load(['customer','items.product']);}
 public function updateStatus(Request $request,Order $order){$data=$request->validate(['status'=>'required|in:pending,confirmed,preparing,out_for_delivery,completed,cancelled']);$old=$order->status;$order->update($data);AdminActivity::create(['action'=>$data['status']==='cancelled'?'order_cancelled':'order_status_changed','subject_type'=>'order','subject_id'=>$order->id,'description'=>"Order {$order->order_number}: {$old} → {$data['status']}"]);return $order->fresh()->load(['customer','items']);}
}
